version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: gestion_ordres_fabrication  # Mise à jour du nom de la base de données
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./src
    container_name: spring-backend
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gestion_ordres_fabrication  # Mise à jour de l'URL de la base de données
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin

  frontend:
    build: ./frontend-project
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data:
