# Étape 1 : build du projet
FROM maven:3.9.6-eclipse-temurin-17 as build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Étape 2 : image finale avec le JAR
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Exposer le port de ton application (modifie si nécessaire)
EXPOSE 8081

# Commande pour exécuter l'app
ENTRYPOINT ["java", "-jar", "app.jar"]
